image: node:12.16.3-stretch

stages:
  - build
  - test
  - release

# variables:
#   ACCESS_TOKEN: 1234...

###############################################################################
## DVOTE SOLIDITY
###############################################################################

dvote-solidity-build:
  stage: build
  script:
    - apt-get install make
    - make all
    - make test
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - build/
  only:
    changes:
      - contracts/**/*
      - lib/**/*
      - test/**/*
      - makefile
      - package-lock.json
      - package.json
      - tsconfig.json
      - .gitlab-ci.yml


# dvote-solidity-test:
#  stage: test
#  script:
#    - apt-get install make
#    - make test


# dvote-solidity-release:
#   stage: release
#   script:
#     - npm ...
#   only:
#     - master
